### ISSUE TITLE
UI tesztek hiánya

### ISSUE THREAD

**Issue by R4zor25** [BME-MIT-IET/iet-hf2021-kotlin-team#1]
2 elem hozzáadása -> egyik törlése -> egy elem maradt, és a megfelelő került törlésre
1 elem hozzáadása ->  az elem módosítása -> értékek megváltoztak-e
Diagram a viewpageren látható-e?
Nem workout (pl lunch) típusúnál 3 elem a viewpagerben (description, diagram, web)
2 elem hozzáadása -> először 'b' nevű, majd 'a' -> rendezés név szerint -> sorrend változott-e?

**Comment by brobi1999** [comment]
A UI teszteket Espresso-val lenne érdemes elkészítenünk. További tesztesetek lehetnének még a következők:

1 elem hozzáadása adatokkal -> egyeznek-e az adatok
2 elem hozzáadása -> Delete All gomb megnyomása -> 0 elem maradt-e a recycler viewban?
Elem hozzáadása leírással -> click() -> viewpager első oldalán megjelnik-e a megadott leírás?
Workout típusú elem felvételénél 2 fragmentből áll-e a ViewPager
2 elem hozzáadása dátum szerint fordított sorrendben-> rendezés date szerint -> sorrend változott-e?
Delete all menüpont kiválasztása -> megjelenik-e a felugró dialog?

Ezeken dolgozhatnánk.
